name: Unit Test
on:
  push:
    branches:
      - main

jobs:
  AbpVnextPrc-CI:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Dotnet 6.x
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: "6.0"
          include-prerelease: True
      - name: Build
        run: dotnet build aspnet-core/QYQ.DataManagement.sln
      - name: Test
        run: dotnet test aspnet-core/services/test/QYQ.DataManagement.Domain.Tests/QYQ.DataManagement.Domain.Tests.csproj
